# Generated by Django 4.2.9 on 2026-10-02 20:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockInCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(verbose_name='链内序号')),
                ('reason', models.TextField(verbose_name='更正理由')),
                ('status', models.CharField(choices=[('pending', '待审批'), ('effective', '已生效'), ('rejected', '已拒绝'), ('withdrawn', '已撤回')], default='pending', max_length=20, verbose_name='状态')),
                ('approver_remark', models.TextField(blank=True, verbose_name='审批意见')),
                ('is_post_reference', models.BooleanField(default=False, verbose_name='是否事后更正（记录已被后续业务引用）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='生效时间')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_stock_in_corrections', to=settings.AUTH_USER_MODEL, verbose_name='批准人')),
                ('proposed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_stock_in_corrections', to=settings.AUTH_USER_MODEL, verbose_name='提交人')),
                ('reverses', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='warehouse.stockincorrection', verbose_name='撤销的目标更正')),
                ('stock_in', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='warehouse.stockin', verbose_name='入库记录')),
            ],
            options={
                'verbose_name': '入库更正单',
                'verbose_name_plural': '入库更正单',
                'db_table': 'wh_stock_in_correction',
                'ordering': ['stock_in', 'sequence'],
                'unique_together': {('stock_in', 'sequence')},
            },
        ),
        migrations.CreateModel(
            name='StockInCorrectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(choices=[('batch_no', '批次号'), ('quantity', '入库数量')], max_length=20, verbose_name='字段')),
                ('old_value', models.CharField(max_length=64, verbose_name='原值')),
                ('new_value', models.CharField(max_length=64, verbose_name='建议值')),
                ('correction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='warehouse.stockincorrection', verbose_name='更正单')),
            ],
            options={
                'verbose_name': '入库更正明细',
                'verbose_name_plural': '入库更正明细',
                'db_table': 'wh_stock_in_correction_item',
                'unique_together': {('correction', 'field_name')},
            },
        ),
    ]
